//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: orca.proto
namespace com.xiaoman
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrcaAdv")]
  public partial class OrcaAdv : global::ProtoBuf.IExtensible
  {
    public OrcaAdv() {}
    
    private ulong _adv_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"adv_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong adv_id
    {
      get { return _adv_id; }
      set { _adv_id = value; }
    }
    private uint _creation_time = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"creation_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint creation_time
    {
      get { return _creation_time; }
      set { _creation_time = value; }
    }
    private uint _expiration_time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"expiration_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint expiration_time
    {
      get { return _expiration_time; }
      set { _expiration_time = value; }
    }
    private byte[] _wall_paper_16_to_9 = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"wall_paper_16_to_9", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] wall_paper_16_to_9
    {
      get { return _wall_paper_16_to_9; }
      set { _wall_paper_16_to_9 = value; }
    }
    private byte[] _wall_paper_4_to_3 = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"wall_paper_4_to_3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] wall_paper_4_to_3
    {
      get { return _wall_paper_4_to_3; }
      set { _wall_paper_4_to_3 = value; }
    }
    private byte[] _div_paper = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"div_paper", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] div_paper
    {
      get { return _div_paper; }
      set { _div_paper = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrcaRequest")]
  public partial class OrcaRequest : global::ProtoBuf.IExtensible
  {
    public OrcaRequest() {}
    
    private com.xiaoman.OrcaCommand _command;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"command", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.xiaoman.OrcaCommand command
    {
      get { return _command; }
      set { _command = value; }
    }
    private com.xiaoman.OrcaRequest.QueryAdsRequest _query_ads_request = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"query_ads_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.xiaoman.OrcaRequest.QueryAdsRequest query_ads_request
    {
      get { return _query_ads_request; }
      set { _query_ads_request = value; }
    }
    private com.xiaoman.OrcaRequest.UpdateAdsRequest _update_ads_request = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"update_ads_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.xiaoman.OrcaRequest.UpdateAdsRequest update_ads_request
    {
      get { return _update_ads_request; }
      set { _update_ads_request = value; }
    }
    private com.xiaoman.OrcaRequest.InsertLogsRequest _insert_logs_request = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"insert_logs_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.xiaoman.OrcaRequest.InsertLogsRequest insert_logs_request
    {
      get { return _insert_logs_request; }
      set { _insert_logs_request = value; }
    }
    private com.xiaoman.OrcaRequest.InsertScreenshotsRequest _insert_screenshots_request = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"insert_screenshots_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.xiaoman.OrcaRequest.InsertScreenshotsRequest insert_screenshots_request
    {
      get { return _insert_screenshots_request; }
      set { _insert_screenshots_request = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryAdsRequest")]
  public partial class QueryAdsRequest : global::ProtoBuf.IExtensible
  {
    public QueryAdsRequest() {}
    
    private com.xiaoman.OrcaRequest.QueryAdsRequest.QueryType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.xiaoman.OrcaRequest.QueryAdsRequest.QueryType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _mac_addr = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mac_addr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mac_addr
    {
      get { return _mac_addr; }
      set { _mac_addr = value; }
    }
    private com.xiaoman.OrcaRequest.QueryAdsRequest.Resolution _resolution = com.xiaoman.OrcaRequest.QueryAdsRequest.Resolution.RES_4_TO_3;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"resolution", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.xiaoman.OrcaRequest.QueryAdsRequest.Resolution.RES_4_TO_3)]
    public com.xiaoman.OrcaRequest.QueryAdsRequest.Resolution resolution
    {
      get { return _resolution; }
      set { _resolution = value; }
    }
    private uint _creation_time = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"creation_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint creation_time
    {
      get { return _creation_time; }
      set { _creation_time = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"QueryType")]
    public enum QueryType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUERY_TYPE_SIMPLE", Value=0)]
      QUERY_TYPE_SIMPLE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUERY_TYPE_COMPLEX", Value=1)]
      QUERY_TYPE_COMPLEX = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Resolution")]
    public enum Resolution
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_4_TO_3", Value=0)]
      RES_4_TO_3 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_16_TO_9", Value=1)]
      RES_16_TO_9 = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateAdsRequest")]
  public partial class UpdateAdsRequest : global::ProtoBuf.IExtensible
  {
    public UpdateAdsRequest() {}
    
    private com.xiaoman.OrcaRequest.UpdateAdsRequest.UpdateType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.xiaoman.OrcaRequest.UpdateAdsRequest.UpdateType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private com.xiaoman.OrcaAdv _adv;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"adv", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.xiaoman.OrcaAdv adv
    {
      get { return _adv; }
      set { _adv = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"UpdateType")]
    public enum UpdateType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE_TYPE_CREATE", Value=0)]
      UPDATE_TYPE_CREATE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE_TYPE_UPDATE", Value=1)]
      UPDATE_TYPE_UPDATE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE_TYPE_DELETE", Value=2)]
      UPDATE_TYPE_DELETE = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InsertLogsRequest")]
  public partial class InsertLogsRequest : global::ProtoBuf.IExtensible
  {
    public InsertLogsRequest() {}
    
    private readonly global::System.Collections.Generic.List<com.xiaoman.OrcaRequest.InsertLogsRequest.PrintLog> _logs = new global::System.Collections.Generic.List<com.xiaoman.OrcaRequest.InsertLogsRequest.PrintLog>();
    [global::ProtoBuf.ProtoMember(1, Name=@"logs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.xiaoman.OrcaRequest.InsertLogsRequest.PrintLog> logs
    {
      get { return _logs; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PrintLog")]
  public partial class PrintLog : global::ProtoBuf.IExtensible
  {
    public PrintLog() {}
    
    private uint _disptime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"disptime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint disptime
    {
      get { return _disptime; }
      set { _disptime = value; }
    }
    private string _pc_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pc_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pc_name
    {
      get { return _pc_name; }
      set { _pc_name = value; }
    }
    private string _mac_addr;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mac_addr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mac_addr
    {
      get { return _mac_addr; }
      set { _mac_addr = value; }
    }
    private string _ip_addr = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ip_addr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip_addr
    {
      get { return _ip_addr; }
      set { _ip_addr = value; }
    }
    private ulong _ad_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ad_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong ad_id
    {
      get { return _ad_id; }
      set { _ad_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InsertScreenshotsRequest")]
  public partial class InsertScreenshotsRequest : global::ProtoBuf.IExtensible
  {
    public InsertScreenshotsRequest() {}
    
    private readonly global::System.Collections.Generic.List<com.xiaoman.OrcaRequest.InsertScreenshotsRequest.ShowLog> _logs = new global::System.Collections.Generic.List<com.xiaoman.OrcaRequest.InsertScreenshotsRequest.ShowLog>();
    [global::ProtoBuf.ProtoMember(1, Name=@"logs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.xiaoman.OrcaRequest.InsertScreenshotsRequest.ShowLog> logs
    {
      get { return _logs; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShowLog")]
  public partial class ShowLog : global::ProtoBuf.IExtensible
  {
    public ShowLog() {}
    
    private uint _disptime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"disptime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint disptime
    {
      get { return _disptime; }
      set { _disptime = value; }
    }
    private string _mac_addr;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mac_addr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mac_addr
    {
      get { return _mac_addr; }
      set { _mac_addr = value; }
    }
    private ulong _ad_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ad_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong ad_id
    {
      get { return _ad_id; }
      set { _ad_id = value; }
    }
    private byte[] _picture;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"picture", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] picture
    {
      get { return _picture; }
      set { _picture = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrcaResponse")]
  public partial class OrcaResponse : global::ProtoBuf.IExtensible
  {
    public OrcaResponse() {}
    
    private com.xiaoman.OrcaCommand _command;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"command", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.xiaoman.OrcaCommand command
    {
      get { return _command; }
      set { _command = value; }
    }
    private com.xiaoman.OrcaResponse.QueryAdsResponse _query_ads_response = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"query_ads_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.xiaoman.OrcaResponse.QueryAdsResponse query_ads_response
    {
      get { return _query_ads_response; }
      set { _query_ads_response = value; }
    }
    private com.xiaoman.OrcaResponse.UpdateAdsResponse _update_ads_response = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"update_ads_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.xiaoman.OrcaResponse.UpdateAdsResponse update_ads_response
    {
      get { return _update_ads_response; }
      set { _update_ads_response = value; }
    }
    private com.xiaoman.OrcaResponse.InsertLogsResponse _insert_logs_response = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"insert_logs_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.xiaoman.OrcaResponse.InsertLogsResponse insert_logs_response
    {
      get { return _insert_logs_response; }
      set { _insert_logs_response = value; }
    }
    private com.xiaoman.OrcaResponse.InsertScreenshotsResponse _insert_screenshots_response = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"insert_screenshots_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.xiaoman.OrcaResponse.InsertScreenshotsResponse insert_screenshots_response
    {
      get { return _insert_screenshots_response; }
      set { _insert_screenshots_response = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryAdsResponse")]
  public partial class QueryAdsResponse : global::ProtoBuf.IExtensible
  {
    public QueryAdsResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.xiaoman.OrcaAdv> _ads = new global::System.Collections.Generic.List<com.xiaoman.OrcaAdv>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ads", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.xiaoman.OrcaAdv> ads
    {
      get { return _ads; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateAdsResponse")]
  public partial class UpdateAdsResponse : global::ProtoBuf.IExtensible
  {
    public UpdateAdsResponse() {}
    
    private bool _succeed;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"succeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool succeed
    {
      get { return _succeed; }
      set { _succeed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InsertLogsResponse")]
  public partial class InsertLogsResponse : global::ProtoBuf.IExtensible
  {
    public InsertLogsResponse() {}
    
    private uint _inserted_logs;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"inserted_logs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint inserted_logs
    {
      get { return _inserted_logs; }
      set { _inserted_logs = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InsertScreenshotsResponse")]
  public partial class InsertScreenshotsResponse : global::ProtoBuf.IExtensible
  {
    public InsertScreenshotsResponse() {}
    
    private uint _inserted_shots;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"inserted_shots", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint inserted_shots
    {
      get { return _inserted_shots; }
      set { _inserted_shots = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"OrcaCommand")]
    public enum OrcaCommand
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORCA_COMMAND_QUERY_ADS", Value=0)]
      ORCA_COMMAND_QUERY_ADS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORCA_COMMAND_UPDATE_ADS", Value=1)]
      ORCA_COMMAND_UPDATE_ADS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORCA_COMMAND_INSERT_LOGS", Value=2)]
      ORCA_COMMAND_INSERT_LOGS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORCA_COMMAND_INSERT_SCREENSHOTS", Value=3)]
      ORCA_COMMAND_INSERT_SCREENSHOTS = 3
    }
  
}